"use client";

import { useState } from "react";
import { createQuotation, editQuotation } from "../actions";

export type CustomerOption = { id: string; name: string };
export type ServiceOption = { id: string; name: string; price: number };
export type QuotationItem = { description: string; quantity: number; unitPrice: number; discount?: number | null };
export type EditableQuotation = { id: string; clientName: string; clientAddress?: string | null; clientTaxId?: string | null; notes?: string | null; discount?: number | null; taxRate?: number | null; items: QuotationItem[] };
type Item = QuotationItem & { id: number };

export function QuotationForm({ customers, services, quotation }: { customers: CustomerOption[]; services: ServiceOption[]; quotation?: EditableQuotation }) {
  const [items, setItems] = useState<Item[]>(() => quotation?.items.length ? quotation.items.map((item, index) => ({ ...item, id: index + 1 })) : [{ id: 1, description: "", quantity: 1, unitPrice: 0, discount: null }]);
  const [quotationDiscount, setQuotationDiscount] = useState<number | null>(quotation?.discount ?? null);
  const [taxRate, setTaxRate] = useState<number | null>(quotation?.taxRate ?? null);
  const subtotal = items.reduce((sum, item) => sum + Math.round(item.quantity * item.unitPrice * (1 - (item.discount ?? 0) / 100)), 0);
  const discountAmount = Math.round(subtotal * (quotationDiscount ?? 0) / 100);
  const taxableAmount = subtotal - discountAmount;
  const tax = Math.round(taxableAmount * (taxRate ?? 0) / 100);
  const total = taxableAmount + tax;
  const format = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
  const isEditing = Boolean(quotation);
  function update(id: number, patch: Partial<Item>) { setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); }

  return <form action={isEditing ? editQuotation : createQuotation} className="space-y-6">
    {quotation && <input type="hidden" name="id" value={quotation.id} />}
    <div className="grid gap-5 sm:grid-cols-2">{isEditing ? <label className="grid gap-2 text-sm font-medium text-slate-700">Cliente<input className="form-control cursor-not-allowed bg-slate-100 text-slate-500" value={quotation?.clientName ?? ""} disabled /><input type="hidden" name="client_name" value={quotation?.clientName ?? ""} /><span className="text-xs font-normal text-slate-500">El cliente no se puede cambiar en una contraoferta.</span></label> : <label className="grid gap-2 text-sm font-medium text-slate-700">Cliente<select className="form-control" name="client_name" required defaultValue=""><option value="" disabled>Selecciona un cliente</option>{customers.map((customer) => <option key={customer.id} value={customer.name}>{customer.name}</option>)}</select></label>}<p className="self-end text-sm text-slate-500">{isEditing ? "Actualiza los valores para preparar una contraoferta." : "La cotización se guardará con la fecha actual y en pesos chilenos."}</p></div>
    <div><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">Servicios</h3><button type="button" onClick={() => setItems((current) => [...current, { id: Date.now(), description: "", quantity: 1, unitPrice: 0, discount: null }])} className="text-sm font-semibold text-blue-700 hover:underline">+ Agregar servicio</button></div><div className="space-y-3">{items.map((item, index) => <div key={item.id} className="grid gap-3 rounded-lg border border-blue-100 p-3 sm:grid-cols-[1fr_90px_130px_105px_auto] sm:items-end"><label className="grid gap-1 text-xs font-medium text-slate-600">Servicio<select className="form-control" name="item_description" required value={item.description} onChange={(event) => { const service = services.find(({ name }) => name === event.target.value); update(item.id, { description: event.target.value, unitPrice: service?.price ?? 0 }); }}><option value="" disabled>Selecciona un servicio</option>{services.map((service) => <option key={service.id} value={service.name}>{service.name}</option>)}</select></label><label className="grid gap-1 text-xs font-medium text-slate-600">Cantidad<input className="form-control" name="item_quantity" type="number" min="1" step="1" required value={item.quantity} onChange={(event) => update(item.id, { quantity: Number(event.target.value) })} /></label><label className="grid gap-1 text-xs font-medium text-slate-600">Precio unitario<input className="form-control" name="item_unit_price" type="number" min="0" step="1" required value={item.unitPrice} onChange={(event) => update(item.id, { unitPrice: Number(event.target.value) })} /></label><label className="grid gap-1 text-xs font-medium text-slate-600">Descuento %<input className="form-control" name="item_discount" type="number" min="0" max="100" step="1" value={item.discount ?? ""} onChange={(event) => update(item.id, { discount: event.target.value === "" ? null : Number(event.target.value) })} /></label><button type="button" aria-label={`Quitar servicio ${index + 1}`} disabled={items.length === 1} onClick={() => setItems((current) => current.filter(({ id }) => id !== item.id))} className="min-h-12 rounded-lg px-3 text-sm font-medium text-red-600 hover:bg-red-50 disabled:opacity-30">Quitar</button></div>)}</div></div>
    <label className="grid gap-2 text-sm font-medium text-slate-700">Observación<textarea className="form-control min-h-24 py-3" name="notes" defaultValue={quotation?.notes ?? ""} placeholder="Condiciones de pago, alcance u observaciones" /></label>
    <div className="grid gap-4 rounded-lg border border-blue-100  p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="grid max-w-48 gap-1 text-sm font-medium text-slate-700">Descuento general %<input className="form-control" name="quotation_discount" type="number" min="0" max="100" step="1" value={quotationDiscount ?? ""} onChange={(event) => setQuotationDiscount(event.target.value === "" ? null : Number(event.target.value))} /></label><label className="grid max-w-48 gap-1 text-sm font-medium text-slate-700">Impuesto / IVA %<input className="form-control" name="tax_rate" type="number" min="0" max="100" step="1" value={taxRate ?? ""} onChange={(event) => setTaxRate(event.target.value === "" ? null : Number(event.target.value))} /><span className="text-xs font-normal text-slate-500">Opcional; define la tasa de tu país.</span></label><div className="text-sm text-slate-600 sm:text-right"><p>Subtotal: <strong>{format.format(subtotal)}</strong></p>{discountAmount > 0 && <p>Descuento: <strong>-{format.format(discountAmount)}</strong></p>}<p>Impuesto{taxRate !== null ? ` (${taxRate}%)` : ""}: <strong>{format.format(tax)}</strong></p><p className="mt-1 text-base">Total: <strong className="text-blue-700">{format.format(total)}</strong></p></div></div>
    <div className="flex justify-end border-t border-blue-100 pt-5"><button className="primary-button">{isEditing ? "Actualizar cotización" : "Guardar cotización"}</button></div>
  </form>;
}
